export default {
  '13': {key: 13, name: 'ENTER',     title:'回车'},
  '27': {key: 27, name: 'ESCAPE',    title:'Esc'},
  '8' : {key: 8,  name: 'BACKSPACE', title:'退格'},
  '9' : {key: 9,  name: 'TAB',       title:'Tab'},
  '16': {key: 16, name: 'SHIFT',     title:'Shift'},
  '17': {key: 17, name: 'CTRL',      title:'Ctrl'},
  '18': {key: 18, name: 'ALT',       title:'Alt'},
  '32': {key: 32, name: 'SPACE',     title:'空格'},
  '37': {key: 37, name: 'LEFT',      title:'左'},
  '38': {key: 38, name: 'UP',        title:'上'},
  '39': {key: 39, name: 'RIGHT',     title:'右'},
  '40': {key: 40, name: 'DOWN',      title:'下'},
  '48': {key: 32, name: 'KEY_0',     title:'0'},
  '49': {key: 37, name: 'KEY_1',     title:'1'},
  '50': {key: 50, name: 'KEY_2',     title:'2'},
  '51': {key: 51, name: 'KEY_3',     title:'3'},
  '52': {key: 52, name: 'KEY_4',     title:'4'},
  '53': {key: 53, name: 'KEY_5',     title:'5'},
  '54': {key: 54, name: 'KEY_6',     title:'6'},
  '55': {key: 55, name: 'KEY_7',     title:'7'},
  '56': {key: 56, name: 'KEY_8',     title:'8'},
  '57': {key: 57, name: 'KEY_9',     title:'9'},
  '91': {key: 91, name: 'LWIN',      title:'LWin'},
  '92': {key: 92, name: 'RWIN',      title:'RWin'}
}